// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qqpxzhxtvdgdedejhcqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFxcHh6aHh0dmRnZGVkZWpoY3FlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NDc5NDMsImV4cCI6MjA2MTQyMzk0M30.e6MPS_zIId29ytbd90X8H_zGnRFigwH6oK04-YcWPq4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);